words = [
    "apiclient",
    "asyncapiclient",
    "autodoc",
    "basemodel",
    "defaultdict",
    "emap",
    "extlinks",
    "furo",
    "githubpages",
    "mro",
    "mutables",
    "pydantics",
    "pyright",
    "queryparams",
    "restfly",
    "retriable",
    "RESTFly",
    "typeadapter",
    "viewcode",
]
