words = [
    "aenter",
    "aexit",
    "apiclient",
    "asyncapiclient",
    "autodoc",
    "basemodel",
    "defaultdict",
    "dunder",
    "emap",
    "extlinks",
    "furo",
    "getitem",
    "githubpages",
    "mro",
    "mutables",
    "pydantics",
    "pyright",
    "queryparams",
    "restfly",
    "retriable",
    "tfly",
    "typeadapter",
    "viewcode",
]
